apiVersion: v1
kind: ConfigMap
metadata:
  namespace: nus-cloud-project
  name: backend-user-routing-hash-generate-springboot-config
data:
  application.yaml: |
    server:
      port: 25558
    
    routingRuleList:
      - startHash: 0
        endHash: 50000000
        index: 0
      - startHash: 50000000
        endHash: 100000000
        index: 1
    
    logging:
      file:
        name: logs/userRoutingHashGenerateService.log
        path: logs/userRoutingHashGenerateService
      level:
        root: INFO
  SPRING_CONFIG_LOCATION: "file:/config/application.yaml"
