apiVersion: v1
kind: ConfigMap
metadata:
  namespace: nus-cloud-project
  name: backend-event-global-data-springboot-config
data:
  application.yaml: |
    server:
      port: 25563
    
    spring:
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}
      rabbitmq:
        host: ${RABBITMQ_HOST}
        port: ${RABBITMQ_PORT}
        virtual-host: ${RABBITMQ_VIRTUAL_HOST}
        username: ${RABBITMQ_USERNAME}
        password: ${RABBITMQ_PASSWORD}
    
    pod-index: ${POD_INDEX}
    
    logging:
      file:
        name: logs/eventGlobalDataService.log
        path: logs/eventGlobalDataService
      level:
        root: INFO
  SPRING_CONFIG_LOCATION: "file:/config/application.yaml"