apiVersion: v1
kind: ConfigMap
metadata:
  namespace: nus-cloud-project
  name: backend-login-springboot-config
data:
  application.yaml: |
    server:
      port: 25560
    
    spring:
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}
      data:
        redis:
          host: ${REDIS_HOST}
          port: ${REDIS_PORT}
          database: 0
    
    logging:
      file:
        name: logs/loginService.log
        path: logs/loginService
      level:
        root: INFO
  SPRING_CONFIG_LOCATION: "file:/config/application.yaml"