apiVersion: v1
kind: ConfigMap
metadata:
  namespace: nus-cloud-project
  name: redis-config
data:
  redis.conf: |
    appendonly yes
    dir /data
  REDIS_HOST_PREFIX: "stateful-set-redis-"  # for saving user data. another one is for events
  REDIS_HOST_POSTFIX: ".headless-service-redis.nus-cloud-project.svc.cluster.local"
  REDIS_PORT: "6379"
