server:
  port: 25563

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nus_cloud
    username: root
    password: 123456

logging:
  file:
    name: logs/eventGlobalDataService.log
    path: logs/eventGlobalDataService
  level:
    root: INFO
