apiVersion: v1
kind: Service
metadata:
  namespace: nus-cloud-project
  name: cluster-ip-service-user-routing-hash-generate
spec:
  type: ClusterIP
  selector:
    backend: user-routing-hash-generate
  ports:
    - port: 25558
