apiVersion: v1
kind: Service
metadata:
  namespace: nus-cloud-project
  name: cluster-ip-service-order-record-0
spec:
  type: ClusterIP
  selector:
    backend: order-record
    apps.kubernetes.io/pod-index: "0"
  ports:
    - port: 25566
---
apiVersion: v1
kind: Service
metadata:
  namespace: nus-cloud-project
  name: cluster-ip-service-order-record-1
spec:
  type: ClusterIP
  selector:
    backend: order-record
    apps.kubernetes.io/pod-index: "1"
  ports:
    - port: 25566
---
apiVersion: v1
kind: Service
metadata:
  namespace: nus-cloud-project
  name: cluster-ip-service-order-record-2
spec:
  type: ClusterIP
  selector:
    backend: order-record
    apps.kubernetes.io/pod-index: "2"
  ports:
    - port: 25566
