apiVersion: v1
kind: Service
metadata:
  namespace: nus-cloud-project
  name: cluster-ip-service-event-publish
spec:
  type: ClusterIP
  selector:
    backend: event-publish
  ports:
    - port: 25564
