apiVersion: v1
kind: Service
metadata:
  namespace: nus-cloud-project
  name: cluster-ip-service-event-detailed-data-0
spec:
  type: ClusterIP
  selector:
    backend: event-detailed-data
    apps.kubernetes.io/pod-index: "0"
  ports:
    - port: 25565
---
apiVersion: v1
kind: Service
metadata:
  namespace: nus-cloud-project
  name: cluster-ip-service-event-detailed-data-1
spec:
  type: ClusterIP
  selector:
    backend: event-detailed-data
    apps.kubernetes.io/pod-index: "1"
  ports:
    - port: 25565
