apiVersion: v1
kind: Service
metadata:
  namespace: nus-cloud-project
  name: cluster-ip-service-register-0
spec:
  type: ClusterIP
  selector:
    backend: register
    apps.kubernetes.io/pod-index: "0"
  ports:
    - port: 25561
---
apiVersion: v1
kind: Service
metadata:
  namespace: nus-cloud-project
  name: cluster-ip-service-register-1
spec:
  type: ClusterIP
  selector:
    backend: register
    apps.kubernetes.io/pod-index: "1"
  ports:
    - port: 25561
