apiVersion: v1
kind: Service
metadata:
  namespace: nus-cloud-project
  name: cluster-ip-service-login-0
spec:
  type: ClusterIP
  selector:
    backend: login
    apps.kubernetes.io/pod-index: "0"
  ports:
    - port: 25560
---
apiVersion: v1
kind: Service
metadata:
  namespace: nus-cloud-project
  name: cluster-ip-service-login-1
spec:
  type: ClusterIP
  selector:
    backend: login
    apps.kubernetes.io/pod-index: "1"
  ports:
    - port: 25560
---
apiVersion: v1
kind: Service
metadata:
  namespace: nus-cloud-project
  name: cluster-ip-service-login-2
spec:
  type: ClusterIP
  selector:
    backend: login
    apps.kubernetes.io/pod-index: "2"
  ports:
    - port: 25560
