apiVersion: v1
kind: Service
metadata:
  namespace: nus-cloud-project
  name: cluster-ip-service-booking-0
spec:
  type: ClusterIP
  selector:
    backend: booking
    apps.kubernetes.io/pod-index: "0"
  ports:
    - port: 25567
---
apiVersion: v1
kind: Service
metadata:
  namespace: nus-cloud-project
  name: cluster-ip-service-booking-1
spec:
  type: ClusterIP
  selector:
    backend: booking
    apps.kubernetes.io/pod-index: "1"
  ports:
    - port: 25567
