apiVersion: v1
kind: Service
metadata:
  namespace: nus-cloud-project
  name: cluster-ip-service-token-verification-0
spec:
  type: ClusterIP
  selector:
    backend: token-verification
    apps.kubernetes.io/pod-index: "0"
  ports:
    - port: 25562
---
apiVersion: v1
kind: Service
metadata:
  namespace: nus-cloud-project
  name: cluster-ip-service-token-verification-1
spec:
  type: ClusterIP
  selector:
    backend: token-verification
    apps.kubernetes.io/pod-index: "1"
  ports:
    - port: 25562
