apiVersion: v1
kind: Service
metadata:
  name: headless-service-redis
  namespace: nus-cloud-project
  labels:
    database: service-redis
spec:
  ports:
    - name: redis
      port: 6379
  selector:
    database: redis
  clusterIP: None
