apiVersion: v1
kind: Service
metadata:
  name: headless-service-mysql-event-global-data
  namespace: nus-cloud-project
  labels:
    database: service-mysql-event-global-data
spec:
  ports:
    - name: mysql
      port: 3306
  selector:
    database: mysql-event-global-data
  clusterIP: None
