apiVersion: v1
kind: Service
metadata:
  namespace: nus-cloud-project
  name: headless-service-register
spec:
  clusterIP: None
  selector:
    backend: register
  ports:
    - port: 25660
      targetPort: 25561