apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: nus-cloud-project
  name: stateful-set-login
spec:
  selector:
    matchLabels:
      backend: login
  serviceName: cluster-ip-service-login
  replicas: 2
  template:
    metadata:
      labels:
        backend: login
    spec:
      containers:
        - name: events-center-backend-login
          image: qy02/events-center-backend-login
          ports:
            - containerPort: 25560
              name: http
          env:
            - name: SPRING_CONFIG_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: backend-login-springboot-config
                  key: SPRING_CONFIG_LOCATION
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: REDIS_HOST_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_HOST_PREFIX
            - name: REDIS_HOST_POSTFIX
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_HOST_POSTFIX
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_PORT
          envFrom:
            - configMapRef:
                name: mysql-user-config
            - configMapRef:
                name: mysql-config
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: backend-login-springboot-config
            items:
              - key: application.yaml
                path: application.yaml
