apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: nus-cloud-project
  name: stateful-set-register
spec:
  selector:
    matchLabels:
      backend: register
  serviceName: headless-service-register
  replicas: 3
  template:
    metadata:
      labels:
        backend: register
    spec:
      containers:
        - name: events-center-backend-register
          image: qy02/events-center-backend-register
          ports:
            - containerPort: 25561
              name: http
          env:
            - name: SPRING_CONFIG_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: backend-register-springboot-config
                  key: SPRING_CONFIG_LOCATION
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          envFrom:
            - configMapRef:
                name: mysql-user-config
            - configMapRef:
                name: mysql-config
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: backend-register-springboot-config
            items:
              - key: application.yaml
                path: application.yaml
