apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: nus-cloud-project
  name: stateful-set-token-verification
spec:
  selector:
    matchLabels:
      backend: token-verification
  serviceName: cluster-ip-service-token-verification
  replicas: 2
  template:
    metadata:
      labels:
        backend: token-verification
    spec:
      containers:
        - name: events-center-backend-token-verification
          image: qy02/events-center-backend-token-verification
          ports:
            - containerPort: 25562
              name: http
          env:
            - name: SPRING_CONFIG_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: backend-token-verification-springboot-config
                  key: SPRING_CONFIG_LOCATION
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_HOST_PREFIX
            - name: REDIS_HOST_POSTFIX
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_HOST_POSTFIX
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_PORT
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: backend-token-verification-springboot-config
            items:
              - key: application.yaml
                path: application.yaml
