apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-set-redis
  namespace: nus-cloud-project
spec:
  selector:
    matchLabels:
      database: redis
  serviceName: headless-service-redis
  replicas: 2
  template:
    metadata:
      labels:
        database: redis
    spec:
      containers:
        - name: events-center-redis
          image: redis:latest
          volumeMounts:
            - name: ebs-storage-redis
              mountPath: /data
            - name: config-volume
              mountPath: /usr/local/etc/redis/
      volumes:
        - name: config-volume
          configMap:
            name: redis-config
            items:
              - key: redis.conf
                path: redis.conf
  volumeClaimTemplates:
    - metadata:
        name: ebs-storage-redis
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "ebs-sc"
        resources:
          requests:
            storage: 1Gi
