apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-set-mysql-event-global-data
  namespace: nus-cloud-project
spec:
  selector:
    matchLabels:
      database: mysql-event-global-data
  serviceName: headless-service-mysql-event-global-data
  replicas: 2
  template:
    metadata:
      labels:
        database: mysql-event-global-data
    spec:
      containers:
        - name: events-center-mysql-event-global-data
          image: qy02/events-center-mysql-event-global-data
          volumeMounts:
            - name: ebs-storage-mysql-event-global-data
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: TZ
              value: "Asia/Shanghai"
  volumeClaimTemplates:
    - metadata:
        name: ebs-storage-mysql-event-global-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "ebs-sc"
        resources:
          requests:
            storage: 1Gi
