apiVersion: v1
kind: Service
metadata:
  #  namespace: nus-cloud-project
  name: register-pod-0-debug
spec:
  ports:
    - protocol: TCP
      port: 25660
      targetPort: 25561
---
apiVersion: v1
kind: Endpoints
metadata:
  #  namespace: nus-cloud-project
  name: register-pod-0-debug
subsets:
  - addresses:
      - ip: 172.31.37.44
    ports:
      - port: 25561