apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-cross-namespace
  namespace: nus-cloud-project
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces: [ "istio-system" ]