apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: nus-cloud-project
  name: http-route-event
spec:
  parentRefs:
    - group: ""
      kind: Service
      name: cluster-ip-service-event
      port: 25661
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /orderRecord
          headers:
            - type: Exact
              name: routingIndex
              value: "0"
      backendRefs:
        - name: cluster-ip-service-order-record-0
          port: 25566
    - matches:
        - path:
            type: PathPrefix
            value: /orderRecord
          headers:
            - type: Exact
              name: routingIndex
              value: "1"
      backendRefs:
        - name: cluster-ip-service-order-record-1
          port: 25566
