apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auto-scaler-stateful-set-reader-binding
subjects:
  - kind: ServiceAccount
    name: auto-scaler-controller-manager
    namespace: auto-scaler-system
roleRef:
  kind: ClusterRole
  name: auto-scaler-stateful-set-reader
  apiGroup: rbac.authorization.k8s.io