apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auto-scaler-stateful-set-reader
rules:
  - apiGroups: [ "apps" ]
    resources: [ "statefulsets" ]
    verbs: [ "get", "list", "watch", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps", "pods" ]
    verbs: [ "get", "list", "watch", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "pods/exec" ]
    verbs: [ "create" ]