apiVersion: autoscaling.my.domain/v1alpha1
kind: AutoScaler
metadata:
  labels:
    app.kubernetes.io/name: autoscaler
    app.kubernetes.io/instance: autoscaler-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: autoscaler-sample
spec:
  # TODO(user): Add fields here
