server:
  port: 25564

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nus_cloud
    username: root
    password: 123456

event-global-data-service:
  host: localhost
  port: 25563

pod-index: 0

logging:
  file:
    name: logs/eventPublishService.log
    path: logs/eventPublishService
  level:
    root: INFO
